name: Bug Report
description: File a bug report
title: "🐞 "
labels: ["bug"]
assignees:
  - demberto
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and a concise description of what happened.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: PyFLP version
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: What code caused this issue?
      render: python3
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Screenshots, Additional info
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow PyFLP's [Code of Conduct](https://github.com/demberto/PyFLP/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
